import AppKit

// Transient dictation is excluded from clipboard histories. Explicit VM copy is not.
func putDictation(_ text: String, on pb: NSPasteboard, transient: Bool = true) {
    pb.clearContents()
    let item = NSPasteboardItem()
    item.setString(text, forType: .string)
    if transient {
        item.setData(Data(), forType: .init("org.nspasteboard.TransientType"))
        item.setData(Data(), forType: .init("org.nspasteboard.AutoGeneratedType"))
    }
    pb.writeObjects([item])
}

func isConcealed(_ items: [NSPasteboardItem]) -> Bool {
    items.contains { $0.types.contains(.init("org.nspasteboard.ConcealedType")) }
}

/// AppKit caches NSPasteboard instances by name. Keep all parent-process access
/// on main; a disposable child reads promised data without sharing that cache.
final class DictationClipboard {
    static let shared = DictationClipboard()
    private static let maxBytes = 16 * 1024 * 1024
    private let name: NSPasteboard.Name
    private var busy = false
    private var reader: Process?
    private var hungMark: Int?
    var isBusy: Bool { busy }
    init(name: NSPasteboard.Name = .general) { self.name = name }

    private struct Flavor: Codable { let type: String; let data: Data }
    private struct Payload: Codable {
        let mark: Int
        var items: [[Flavor]]?
        var text: String?
    }
    private static func executablePath(_ pid: pid_t) -> String? {
        var bytes = [CChar](repeating: 0, count: 4096)
        guard proc_pidpath(pid, &bytes, UInt32(bytes.count)) > 0 else { return nil }
        return String(cString: bytes)
    }

    /// Called before NSApplication startup, also by the standalone test binary.
    static func runReaderIfRequested() {
        let args = CommandLine.arguments
        guard args.count == 3, ["--giga-pb-snapshot", "--giga-pb-text"].contains(args[1]) else { return }
        guard getppid() > 1, let ownPath = executablePath(getpid()),
              executablePath(getppid()) == ownPath else { _exit(2) }
        signal(SIGALRM, SIG_DFL)
        alarm(6) // bounds lifetime even if the parent crashes
        let pb = NSPasteboard(name: .init(args[2]))
        let mark = pb.changeCount
        var result = Payload(mark: mark)
        if args[1] == "--giga-pb-text" {
            if !(pb.types?.contains(.fileURL) ?? false), let text = pb.string(forType: .string) {
                guard text.utf8.count <= maxBytes else { _exit(2) }
                result.text = text
            }
        } else {
            var total = 0
            var items = [[Flavor]]()
            for item in pb.pasteboardItems ?? [] {
                guard items.count < 128 else { _exit(2) }
                var values = [Flavor]()
                if item.types.contains(.init("org.nspasteboard.ConcealedType")) {
                    items.append([Flavor(type: "org.nspasteboard.ConcealedType", data: Data())])
                    continue
                }
                for type in item.types {
                    if let data = item.data(forType: type) {
                        total += data.count
                        guard total <= maxBytes else { _exit(2) }
                        values.append(Flavor(type: type.rawValue, data: data))
                    }
                }
                items.append(values)
            }
            result.items = items
        }
        guard pb.changeCount == mark,
              let data = try? PropertyListEncoder().encode(result),
              data.count <= maxBytes else { _exit(2) }
        FileHandle.standardOutput.write(data)
        _exit(0)
    }

    private func readInChild(_ mode: String, done: @escaping (Payload?, Bool) -> Void) {
        dispatchPrecondition(condition: .onQueue(.main))
        guard reader == nil, let executable = Self.executablePath(getpid()) else { done(nil, false); return }
        let process = Process(), pipe = Pipe()
        let input = pipe.fileHandleForReading, output = pipe.fileHandleForWriting
        guard fcntl(input.fileDescriptor, F_SETFD, FD_CLOEXEC) == 0,
              fcntl(output.fileDescriptor, F_SETFD, FD_CLOEXEC) == 0,
              fcntl(input.fileDescriptor, F_SETFL, O_NONBLOCK) == 0 else { done(nil, false); return }
        process.executableURL = URL(fileURLWithPath: executable)
        process.arguments = [mode, name.rawValue]
        process.standardOutput = pipe
        process.standardInput = FileHandle.nullDevice
        process.standardError = FileHandle.nullDevice
        process.qualityOfService = .userInitiated
        var answered = false // main only
        func finish(_ result: Payload?, timedOut: Bool = false) {
            guard !answered else { return }
            answered = true; done(result, timedOut)
        }
        let io = DispatchQueue(label: "ru.panda.giga.clipboard.pipe")
        let source = DispatchSource.makeReadSource(fileDescriptor: input.fileDescriptor, queue: io)
        var data = Data(), invalid = false, eof = false // io queue only
        func drain() {
            guard !eof else { return }
            var bytes = [UInt8](repeating: 0, count: 65536)
            while true {
                let count = Darwin.read(input.fileDescriptor, &bytes, bytes.count)
                if count > 0 {
                    if data.count + count <= Self.maxBytes, !invalid {
                        data.append(contentsOf: bytes.prefix(count))
                    } else {
                        invalid = true
                        DispatchQueue.main.async {
                            if process.isRunning { kill(process.processIdentifier, SIGKILL) }
                        }
                        return
                    }
                } else if count == 0 { eof = true; return }
                else if errno == EINTR { continue }
                else if errno == EAGAIN || errno == EWOULDBLOCK { return }
                else { invalid = true; return }
            }
        }
        source.setEventHandler {
            drain()
            if eof { source.setEventHandler {}; source.cancel() }
        }
        source.setCancelHandler { try? input.close() }
        process.terminationHandler = { ended in
            ended.terminationHandler = nil
            DispatchQueue.main.async {
                if self.reader === ended { self.reader = nil }
            }
            io.async {
                drain() // read remaining bytes, never wait for EOF from an inherited fd
                source.setEventHandler {}
                source.cancel()
                let result = !invalid && ended.terminationReason == .exit && ended.terminationStatus == 0
                    ? try? PropertyListDecoder().decode(Payload.self, from: data) : nil
                DispatchQueue.main.async { finish(result) }
            }
        }
        do { try process.run() }
        catch {
            process.terminationHandler = nil
            source.setEventHandler {}
            source.cancel(); source.resume()
            finish(nil); return
        }
        reader = process
        try? output.close()
        source.resume()
        DispatchQueue.main.asyncAfter(deadline: .now() + 3) {
            guard !answered else { return }
            if process.isRunning {
                kill(process.processIdentifier, SIGKILL)
                finish(nil, timedOut: true)
            }
        }
    }

    private struct Snapshot {
        let mark: Int
        let items: [[Flavor]]
    }
    private var board: NSPasteboard {
        dispatchPrecondition(condition: .onQueue(.main))
        return NSPasteboard(name: name)
    }

    private func snapshot(_ done: @escaping (Snapshot?) -> Void) {
        let mark = board.changeCount
        guard !busy, reader == nil, hungMark != mark else { done(nil); return }
        busy = true
        readInChild("--giga-pb-snapshot") { result, timedOut in
            guard let result, result.mark == mark, self.board.changeCount == mark,
                  let items = result.items else {
                if timedOut { self.hungMark = mark }
                self.busy = false; done(nil); return
            }
            self.hungMark = nil
            done(Snapshot(mark: mark, items: items))
        }
    }

    func readText(_ done: @escaping (String?) -> Void) {
        snapshot { saved in
            guard let saved else { done(nil); return }
            self.busy = false
            let value = saved.items.first?.first(where: { $0.type == NSPasteboard.PasteboardType.string.rawValue })?.data
            done(value.flatMap { String(data: $0, encoding: .utf8) })
        }
    }

    private func restore(_ saved: Snapshot, ifMark mark: Int) {
        let pb = board
        guard pb.changeCount == mark else { return }
        pb.clearContents()
        guard !saved.items.contains(where: { $0.contains(where: { $0.type == "org.nspasteboard.ConcealedType" }) }) else { return }
        let items = saved.items.map { value -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for flavor in value { item.setData(flavor.data, forType: .init(flavor.type)) }
            return item
        }
        if !items.isEmpty { pb.writeObjects(items) }
    }

    func paste(_ text: String, keepOnClipboard: Bool = false, stale: @escaping () -> Bool = { false }, allowed: @escaping () -> Bool,
               action: @escaping (@escaping () -> Bool, @escaping (Bool) -> Void) -> Void, failed: @escaping () -> Void) {
        let until = Date().addingTimeInterval(7)
        func admit() {
            guard !stale() else { failed(); return }
            if (self.busy || self.reader != nil) && Date() < until {
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.05, execute: admit)
            } else if self.busy || self.reader != nil { failed() }
            else { self.performPaste(text, keepOnClipboard: keepOnClipboard, stale: stale, allowed: allowed, action: action, failed: failed) }
        }
        admit()
    }

    private func performPaste(_ text: String, keepOnClipboard: Bool, stale: @escaping () -> Bool, allowed: @escaping () -> Bool,
                             action: @escaping (@escaping () -> Bool, @escaping (Bool) -> Void) -> Void,
                             failed: @escaping () -> Void) {
        let originalMark = board.changeCount
        func write(_ saved: Snapshot?) {
            guard !stale(), allowed() || keepOnClipboard,
                  self.board.changeCount == (saved?.mark ?? originalMark) else {
                self.busy = false; failed(); return
            }
            self.busy = true
            putDictation(text, on: self.board, transient: !keepOnClipboard)
            let mark = self.board.changeCount
            guard !stale(), allowed() else {
                if let saved, !keepOnClipboard { self.restore(saved, ifMark: mark) }
                self.busy = false; failed(); return
            }
            action({ self.board.changeCount == mark }) { restore in
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
                    if let saved, restore && !keepOnClipboard { self.restore(saved, ifMark: mark) }
                    self.busy = false
                }
            }
        }
        if hungMark == originalMark || keepOnClipboard { write(nil); return }
        snapshot { saved in
            guard saved != nil || self.hungMark == originalMark else { failed(); return }
            write(saved)
        }
    }

    enum Selection: Equatable { case text(String), noChange, failed }
    func selection(allowed: @escaping () -> Bool, copy: @escaping () -> Void,
                   done: @escaping (Selection) -> Void) {
        let admissionDeadline = Date().addingTimeInterval(1)
        func admit() {
            guard allowed() else { done(.failed); return }
            if (self.busy || self.reader != nil) && Date() < admissionDeadline {
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.05, execute: admit)
            } else { self.captureSelection(allowed: allowed, copy: copy, done: done) }
        }
        admit()
    }

    private func captureSelection(allowed: @escaping () -> Bool, copy: @escaping () -> Void,
                                  done: @escaping (Selection) -> Void) {
        snapshot { saved in
            guard let saved else { done(.failed); return }
            guard allowed() else { self.busy = false; done(.failed); return }
            let copyDeadline = Date().addingTimeInterval(0.8)
            copy()
            func poll() {
                let mark = self.board.changeCount
                if mark == saved.mark, Date() < copyDeadline {
                    DispatchQueue.main.asyncAfter(deadline: .now() + 0.05, execute: poll)
                    return
                }
                guard mark != saved.mark else { self.busy = false; done(allowed() ? .noChange : .failed); return }
                self.readInChild("--giga-pb-text") { result, _ in
                    let text = result?.mark == mark ? result?.text : nil
                    self.restore(saved, ifMark: mark)
                    self.busy = false
                    done(allowed() ? text.map(Selection.text) ?? .failed : .failed)
                }
            }
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.05, execute: poll)
        }
    }
}
